name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: 178.128.61.248
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/var/www/backend"
          
      - name: Run install and restart
        uses: appleboy/ssh-action@master
        with:
          host: 178.128.61.248
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/backend
            npm install
            pm2 restart backend
